# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 3000

# A continuation prompt that displays two filled in arrows
continuation_prompt = 'â–¶â–¶ '

[battery]
disabled = false
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold #bb9af7)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = '[âœ—](bold red) ' # The 'error_symbol' segment is being set to 'âœ' with the color 'bold red'
vimcmd_symbol = '[âœ](bold #bb9af7)'

[cmd_duration]
format = "[$duration]($style)"
min_time = 300
show_milliseconds = false
style = 'bold italic #bb9af7 bg:none'

[directory]
home_symbol = "ï€• "
read_only = " ï€£ "
truncation_length = 2

[git_branch]
symbol = "ğŸŒ± "

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_metrics]
format = '([+$added]($added_style)/)([-$deleted]($deleted_style) )'
disabled = false
